# Generated by Django 5.1.1 on 2024-11-02 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_rename_volunteer_donation_volunteer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='collectionloc',
            field=models.CharField(max_length=300, null=True, verbose_name='Collection Location'),
        ),
    ]
