# Generated by Django 5.1.1 on 2024-11-02 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_alter_donation_collectionloc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='deliverypic',
            field=models.ImageField(blank=True, null=True, upload_to='delivery_pics/'),
        ),
    ]
